source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SCNavigationControlCenter_Example', :exclusive => true do
  pod "SCNavigationControlCenter", :path => "../"
end

target 'SCNavigationControlCenter_Tests', :exclusive => true do
  pod "SCNavigationControlCenter", :path => "../"

  
end
